# ROI Agent Enhanced Configuration
# Real data only - no test data
monitor:
  interval: 15  # seconds
  data_retention_days: 30
  use_real_data_only: true
  
network:
  monitor_ports: [80, 443, 8080, 3000, 5000, 8000, 9000]
  monitor_protocols: ["HTTP", "HTTPS", "TCP"]
  dns_resolution: true
  packet_capture: true
  real_connections_only: true
  
web:
  host: "127.0.0.1"
  port: 5002
  auto_refresh: 30  # seconds
  
security:
  require_accessibility: true
  local_only: true
  
debug:
  enable_test_data: false  # Always use real data
  log_level: "info"