# ROI Agent Enhanced Configuration
# DNS Snooping based network monitoring
monitor:
  interval: 15  # seconds
  data_retention_days: 30
  use_real_data_only: true
  
network:
  dns_snooping: true
  monitor_ports: [80, 443, 8080, 3000, 5000, 8000, 9000]
  monitor_protocols: ["HTTP", "HTTPS", "TCP"]
  tcpdump_packet_count: 50  # Number of packets to capture per session
  requires_sudo: true
  real_connections_only: true
  
web:
  host: "127.0.0.1"
  port: 5002
  auto_refresh: 30  # seconds
  
security:
  require_accessibility: true
  require_sudo: true  # Required for DNS snooping
  local_only: true
  
debug:
  enable_test_data: false  # Always use real data
  log_level: "info"