#!/bin/bash

# ROI Agent Data Transmission Setup Script

echo "🚀 ROI Agent Data Transmission Setup"
echo "===================================="

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "Project root: $PROJECT_ROOT"

# Build data sender
echo "🔨 Building data sender..."
cd "$PROJECT_ROOT/data-sender"
go build -o data-sender main.go
if [ $? -eq 0 ]; then
    echo "✅ Data sender built successfully"
else
    echo "❌ Failed to build data sender"
    exit 1
fi

# Show usage instructions
echo ""
echo "📋 Setup Instructions:"
echo "====================="
echo ""
echo "1. Configure data transmission:"
echo "   ./data-sender config"
echo ""
echo "2. Enable transmission (replace with your actual URL and API key):"
echo "   ./data-sender enable https://api.yourserver.com/v1/roi-agent your-api-key-here"
echo ""
echo "3. Test data transmission:"
echo "   ./data-sender process"
echo ""
echo "4. Disable transmission:"
echo "   ./data-sender disable"
echo ""
echo "📊 What data is sent every 10 minutes:"
echo "====================================="
echo "Applications:"
echo "  - Currently active app name"
echo "  - Currently focused app name"
echo "  - Focus time in seconds"
echo ""
echo "Networks:"
echo "  - FQDN (e.g., www.example.com)"
echo "  - Port number (e.g., 443)"
echo "  - Access count in 10-minute period"
echo "  - Protocol (HTTP/HTTPS)"
echo ""
echo "Metadata:"
echo "  - Device ID (unique identifier)"
echo "  - OS version"
echo "  - Agent version"
echo "  - Total apps and domains count"
echo ""
echo "🔒 Security Notes:"
echo "================="
echo "- Data transmission is DISABLED by default"
echo "- Configuration stored in ~/.roiagent/transmission_config.json"
echo "- Transmission logs saved in ~/.roiagent/transmission/"
echo "- All data is sent over HTTPS"
echo "- API key authentication required"
echo ""
echo "🔧 Manual Commands:"
echo "=================="
echo "# Build data sender"
echo "cd data-sender && go build -o data-sender main.go"
echo ""
echo "# Check configuration"
echo "./data-sender/data-sender config"
echo ""
echo "# Enable transmission"
echo "./data-sender/data-sender enable <BASE_URL> <API_KEY>"
echo ""
echo "# Process current data"
echo "./data-sender/data-sender process"
echo ""
echo "📁 File Structure After Setup:"
echo "=============================="
echo "~/.roiagent/"
echo "├── data/                    # Monitoring data"
echo "├── logs/                    # Agent logs"
echo "├── transmission/            # Transmission logs"
echo "└── transmission_config.json # Transmission config"
echo ""
echo "✅ Setup complete! Use the commands above to configure data transmission."
